---


- name: Configure apache CKAN
  template:
    src: apache/ckan_default.conf.j2
    dest: /etc/apache2/sites-enabled/ckan_default.conf

- name: Configure apache Datapusher
  template:
    src: apache/datapusher.conf.j2
    dest: /etc/apache2/sites-enabled/datapusher.conf

- name: Configure apache
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: "^ErrorLog.*"
    line: ErrorLog /proc/self/fd/1

- name: Configure CKAN
  template:
    src: ckan/production.ini.j2
    dest: "{{ CKAN_CONFIG }}/{{ CKAN_CONFIG_FILE }}"

- name: Add licenses JSON file
  template:
    src: ckan/licenses.json.j2
    dest: "{{ CKAN_DIST_CONFIG }}/licenses.json"

- name: Configure supervisor
  template:
    src: ckan/supervisor-ckan-worker.conf.j2
    dest: "/etc/supervisor/conf.d/supervisor-ckan-worker.conf"

- name: Copy portal configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: apache/apache.wsgi.j2, dest: "{{ CKAN_CONFIG }}/apache.wsgi"}
    - {src: ckan/datapusher.wsgi.j2, dest: /etc/ckan/datapusher.wsgi}

- name: Replace Recline styles
  copy:
    src: "recline/recline.min.css"
    dest: "{{ CKAN_HOME }}/src/ckan/ckanext/reclineview/theme/public/css/recline.min.css"

- name: Replace TMS with IGN
  copy:
    src: "recline/recline.js"
    dest: "{{ CKAN_HOME }}/src/ckan/ckanext/reclineview/theme/public/vendor/recline/recline.js"

- name: Add user configuration scripts
  template:
    src: "scripts/config/{{ item.src }}"
    dest: "{{ CKAN_INIT }}/{{ item.dest }}"
  with_items:
    - {src: init_db.sh.j2, dest: "init_db.sh"}
    - {src: make_conf.sh.j2, dest: "make_conf.sh"}
    - {src: add_admin.sh.j2, dest: "add_admin.sh"}
    - {src: change_datapusher_url.sh.j2, dest: "change_datapusher_url.sh"}
    - {src: change_site_url.sh.j2, dest: "change_site_url.sh"}
    - {src: init.sh, dest: "init.sh"}
    - {src: init_dev.sh, dest: "init_dev.sh"}
    - {src: paster.sh.j2, dest: "paster.sh"}
    - {src: update_conf.sh.j2, dest: "update_conf.sh"}
    - {src: upgrade_db.sh, dest: "upgrade_db.sh"}
    - {src: build-combined-ckan-mo.sh, dest: "build-combined-ckan-mo.sh"}
    - {src: run_updates.sh.j2, dest: "run_updates.sh"}

- name: Add run scripts
  template:
    src: "scripts/{{ item.src }}"
    dest: "{{ CKAN_INIT }}/{{ item.dest }}"
  with_items:
    - {src: start_ckan.sh.j2, dest: start_ckan.sh}
    - {src: run_andino.sh, dest: run_andino.sh}
    - {src: run_tests.sh.j2, dest: run_tests.sh}
    - {src: run_rebuild_search.sh.j2, dest: run_rebuild_search.sh}
    - {src: run_update_tracking.sh.j2, dest: run_update_tracking.sh}
    - {src: start_rebuild_cron.sh.j2, dest: start_rebuild_cron.sh}
    - {src: sync_rebuild_tasks.sh.j2, dest: sync_rebuild_tasks.sh}
    - {src: update_data_json_and_catalog_xlsx.sh.j2, dest: update_data_json_and_catalog_xlsx.sh}

- name: Add update scripts
  template:
    src: "scripts/config/updates/{{ item }}.j2"
    dest: "{{ UPDATE_DIR }}{{ item }}"
  with_items:
    - 0001_fix_emails.sh
    - 0002_add_google_analytics_config.sh
    - 0003_fix_flask_version.sh
    - 0004_add_dcat_and_structured_data_config.sh
    - 0005_add_series_api_uri_default_value.sh
    - 0006_remove_harvest_and_datajson_plugins.sh

- name: Add tests scripts
  template:
    src: "scripts/tests/{{ item.src }}"
    dest: "{{ CKAN_INIT }}/tests/{{ item.dest }}"
  with_items:
    - {src: install_nodejs.sh.j2, dest: install_nodejs.sh}
    - {src: install_solr4.sh.j2, dest: install_solr4.sh}
    - {src: init_tests.sh.j2, dest: init_tests.sh}
    - {src: run_tests.sh.j2, dest: run_tests.sh}
    - {src: run_testsjs.sh.j2, dest: run_testsjs.sh}
    - {src: run_solr4.sh.j2, dest: run_solr4.sh}
    - {src: run_all_tests.sh.j2, dest: run_all_tests.sh}

- name: Copy default ckan config
  template:
    src: ckan/default.json.j2
    dest: "{{ CKAN_DIST_CONFIG }}/settings.json"

- name: Change mode default ckan config
  file:
    path: "{{ CKAN_DIST_CONFIG }}/settings.json"
    mode: 0666

- name: Change mode ckan init
  file:
    path: "{{ CKAN_INIT }}"
    recurse: yes
    mode: 0777

- name: Change mode ckan config
  file:
    path: "{{ CKAN_CONFIG }}"
    recurse: yes
    mode: 0777
